version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: redoc-cli
        versions:
          - '> 0.10.1, < 1'
      - dependency-name: '@openapitools/openapi-generator-cli'
        versions:
          - 2.1.19
          - 2.1.20
          - 2.1.21
          - 2.1.22
          - 2.1.23
          - 2.1.24
          - 2.1.25
          - 2.1.26
          - 2.2.1
          - 2.2.2
          - 2.2.3
          - 2.2.4
          - 2.2.5
      - dependency-name: typescript
        versions:
          - 4.1.4
          - 4.1.5
          - 4.2.2
          - 4.2.3
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
