openapi: 3.0.1
info:
  title: Mail-in-a-Box
  description: "This is the Mail-in-a-Box API HTTP specification."
  contact:
    email: willis.rh@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Mail-in-a-box
  url: https://mailinabox.email/
servers:
  - url: https://{host}/admin
    variables:
      host:
        default: box.example.com
        description: The API hostname
security:
  - basicAuth: []
tags:
  - name: user
    description: Endpoints related to users
  - name: system
    description: Endpoints related to system
paths:
  /me:
    get:
      tags:
        - user
      summary: Get user information
      operationId: getMe
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeResponse"
  /system/status:
    post:
      tags:
        - system
      summary: Retrieve system status
      operationId: getStatus
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemStatusResponse"
  /system/privacy:
    get:
      tags:
        - system
      summary: Retrieve new-version check status
      operationId: getPrivacy
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemGetPrivacyResponse"
    post:
      tags:
        - system
      summary: Update new-version check status
      operationId: updatePrivacy
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/SystemUpdatePrivacyRequest"
      responses:
        200:
          description: Successful operation
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/SystemUpdatePrivacyResponse"

  /system/reboot:
    get:
      tags:
        - system
      summary: Retrieve reboot status
      operationId: getReboot
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemRebootResponse"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    SystemUpdatePrivacyRequest:
      type: object
      required:
        - value
      properties:
        value:
          type: string
          enum:
            - private
            - "off"
    SystemGetPrivacyResponse:
      type: boolean
      description: |
        Response:
        * `true`: Private, new-version checks will not be performed
        * `false`: Not private, new-version checks will be performed
    SystemUpdatePrivacyResponse:
      type: string
    SystemRebootResponse:
      type: boolean
      description: |
        Response:
        * `true`: A reboot is required
        * `false`: A reboot is not requir
    SystemStatusResponse:
      type: array
      items:
        $ref: "#/components/schemas/StatusEntry"
    StatusEntry:
      type: object
      required:
        - type
        - text
        - extra
      properties:
        type:
          type: string
          enum:
            - heading
            - ok
            - warning
            - error
        text:
          type: string
        extra:
          type: array
          items:
            $ref: "#/components/schemas/StatusEntryExtra"
    StatusEntryExtra:
      type: object
      required:
        - monospace
        - text
      properties:
        monospace:
          type: string
        text:
          type: string
    MeResponse:
      type: object
      required:
        - status
      properties:
        api_key:
          type: string
        email:
          type: string
        privileges:
          type: array
          items:
            type: string
        reason:
          type: string
        status:
          type: string
          enum:
            - ok
            - invalid
