openapi: 3.0.1
info:
  title: Mail-in-a-Box
  description: "This is the Mail-in-a-Box API HTTP specification."
  contact:
    email: willis.rh@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Mail-in-a-box
  url: https://mailinabox.email/
servers:
  - url: https://{host}/admin
    variables:
      host:
        default: box.example.com
        description: The API hostname
security:
  - basicAuth: []
tags:
  - name: user
    description: Endpoints related to users
  - name: system
    description: Endpoints related to system
paths:
  /me:
    get:
      tags:
        - user
      summary: Get user information
      operationId: me
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeResponse"
  /system/status:
    post:
      tags:
        - system
      summary: Restrieve system status
      operationId: status
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemStatusResponse"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    SystemStatusResponse:
      type: array
      items:
        $ref: "#/components/schemas/StatusEntry"
    StatusEntry:
      type: object
      required:
        - type
        - text
        - extra
      properties:
        type:
          type: string
          enum:
            - heading
            - ok
            - error
        text:
          type: string
        extra:
          type: array
          items:
            $ref: "#/components/schemas/StatusEntryExtra"
    StatusEntryExtra:
      type: object
      required:
        - monospace
        - text
      properties:
        monospace:
          type: string
        text:
          type: string
    MeResponse:
      type: object
      required:
        - status
      properties:
        api_key:
          type: string
        email:
          type: string
        privileges:
          type: array
          items:
            type: string
        reason:
          type: string
        status:
          type: string
          enum:
            - ok
            - invalid
