name: Build & Publish
on:
  push:
  release:
    types: [published]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - name: Install dependencies
        run: |
          npm install
      - name: Validate
        run: |
          npm run validate
