name: Build & Publish
on:
  push:
  release:
    types: [published]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Validate
        run: |
          npm run validate
  build-and-publish-typescript-fetch:
    needs: [validate]
    name: Build and publish typescript-fetch
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Build typescript-fetch client
        run: |
          npm run generate:typescript-fetch
      - name: Publish typescript-fetch package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd clients/typescript-fetch
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish
  build-and-publish-php:
    needs: [validate]
    name: Build and publish php
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Checkout package source
        uses: actions/checkout@v2
        with:
          repository: badsyntax/mailinabox-api-php
          path: clients/php
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
      - name: Clean package source
        run: |
          cd clients/php
          git rm -rf .
          git clean -fxd
      - name: Build php client
        run: |
          npm run generate:php
      - name: Push changes to package source
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "TAG: $tag"
          tag="0.0.0"
          cd clients/php
          echo -e "\n## Tagged Version\n\n$tag" >> README.md
          git config user.name "Richard Willis"
          git config user.email "willis.rh@gmail.com"
          git add .
          git commit -m "Generate code for version $tag"
          git push
          git tag "$tag"
          git push --tags
      # - name: Publish php package
      #   run: |
